[project]
name = "function-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.5.5",
    "httpx>=0.28.1",
    "openai-agents>=0.0.19",
    "requests>=2.32.4",
    "rich>=14.0.0",
]
